name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        cd 01_DB
        docker build . --file Dockerfile.single --tag geo-db:$(date +%s)

    - name: Push Docker image
      run: docker push geo-db
