name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Create tag
      run: export tag_name=$(date +%s)
      
    - name: Build the Docker image
      run: |
        cd 01_DB
        docker build . --file Dockerfile.single --tag geo-db:$tag_name

    - name: Push Docker image
      run: docker push geo-db:$tag_name
